matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
script:
  - >-
    ./.travis/decrypt.sh &&
    yarn electron-webpack prod &&
    ./.scripts/copy-module.js
      --bin npm
      --bin yarn
      --bin patternplate
      --bin get-port
      --out local_modules
      --mod electron-screenshot-service
      --ignore electron &&
    travis_wait yarn electron-builder
