matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
before_install:
  - brew install gnu-tar
script:
  - >-
    yarn electron-webpack prod --env.minify=false &&
    cd node_modules &&
    gtar -cf ../node_modules.tar . &&
    cd - &&
    yarn electron-builder --publish=always
